### ISSUE TITLE
Minimal skeleton Ecto.Adapter using the Antidote Erlang Client.

### ISSUE THREAD

**Issue by thruflo** [vaxine-io/vax#2]
As per the [spikes/adapter](https://github.com/vaxine-io/vax/tree/spikes/adapter) branch, we need a working Ecto adapter code structure that uses the existing Antidote erlang client as the driver.

Success for this epic consists in being able to retrieve some data using Ecto.Repo

Tasks:
 - [x] Establish a connection Antidote (done in #12)
 - [ ] Support maps in antidote client
 - [ ] Insert schemas as maps
 - [ ] Read maps as schemas
 - [ ] Update schemas as maps
