### ISSUE TITLE
Store rows as a CRDT map object.

### ISSUE THREAD

**Issue by thruflo** [vaxine-io/vax#5]
We need to handle inserting and updating schema structs and changesets through the Repo.insert and Repo.update machinery as an Antidote map.

- [ ] handle `Changeset.apply_changes` as per #4 
- [ ] implement `Repo.insert`
- [ ] implement `Repo.update`
